
server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/lin034/repasaSpringCloudConfig.git
          search-paths: config-data
  application:
    name: config-servicio